version: 0.0
Resources:
  - myK8sDeployment:
      Type: AWS::EKS::Manifest
      Properties:
        ClusterName: brain-cluster
        RoleArn: arn:aws:iam::251221984734:role/CodeDeployRole
        ManifestPaths:
          - deployment.yaml
          - service.yaml
