version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ECR_REPO: brain-tasks-app
phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $ECR_URI:$IMAGE_TAG
      - echo "Substituting image URI in deployment manifest..."
      - sed -i "s|IMAGE_URI|$ECR_URI:$IMAGE_TAG|g" deployment.yaml
artifacts:
  files:
    - appspec.yml
    - deployment.yaml
    - service.yaml
