version: 0.2

env:
  variables:
    APP_NAME: "brain-tasks-app"
  parameter-store:
    # Optional: set ACCOUNT_ID and AWS_DEFAULT_REGION in Parameter Store and reference them here
    # ACCOUNT_ID: "/cicd/account_id"
    # AWS_DEFAULT_REGION: "/cicd/region"
phases:
  install:
    commands:
      - echo "Install utilities"
      - apt-get update -y && apt-get install -y jq
  pre_build:
    commands:
      - echo "Pre-build: set variables and login to ECR"
      - '[ -z "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION=$(aws configure get region) || true'
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_NAME}
      - aws ecr describe-repositories --repository-names ${APP_NAME} >/dev/null 2>&1 || aws ecr create-repository --repository-name ${APP_NAME}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo "Build & push image: $REPOSITORY_URI:$IMAGE_TAG"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Render Kubernetes manifest with the new image tag"
      - mkdir -p rendered
      - sed "s|IMAGE_URI|$REPOSITORY_URI:$IMAGE_TAG|g" k8s/deployment.yaml > rendered/deployment.yaml
      - cp k8s/service.yaml rendered/service.yaml
artifacts:
  files:
    - rendered/deployment.yaml
    - rendered/service.yaml
