version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    REPOSITORY_URI: "251221984734.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing deps...
      - aws --version
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating kubernetes deployment image...
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name brain-cluster
      - kubectl set image deployment/brain-deployment brain=$REPOSITORY_URI:$IMAGE_TAG --record
artifacts:
  files:
    - imagedefinitions.json
