apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-deploy
  labels:
    app: brain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      containers:
        - name: brain-container
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:v1 # replaced in CI/CD later
          ports:
            - containerPort: 80
