apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
  labels:
    app: brain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      containers:
      - name: brain
        image: IMAGE_URI
        ports:
        - containerPort: 80
