apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-svc
  labels:
    app: brain-tasks-app
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
